In [50]:
import numpy as np
import pandas as pd

import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

from scipy import stats
import matplotlib.pyplot as plt

HS/MS

In [51]:
enroll = pd.read_excel("Vermont Data/Vermont Enrollment Info.xlsx")
enroll = enroll[enroll["SchoolYear"] == 2022][["SchoolIdentifier", "OrganizationName", "Preschool", "Preschool", "KindergartenFullTime", "KindergartenPartTime", "FirstGrade", "SecondGrade", "ThirdGrade", "FourthGrade", "FifthGrade", "SixthGrade", "SeventhGrade", "EighthGrade", "NinethGrade", "TenthGrade", "EleventhGrade", "TwelvethGrade", "Total"]].reset_index(drop=True)

info = pd.read_csv("Vermont Data/Vermont Science Data.csv")
info = info[info["SY"] == 2022][info["AssessGroup"] == "All Students"][info["Indicator_Label"] == "Average Scaled Score"].reset_index(drop=True)

sciscore = {}
infoorg = list(info["OrganizationIdentifier"])

for school in enroll["SchoolIdentifier"]:
    if school in infoorg:
        scilist = (info[info["OrganizationIdentifier"] == school]["SchoolValue"])
        totalsum = 0
        totalcount = 0
        for val in scilist:
            if "." in val:
                totalsum += float(val)
                totalcount += 1
        
        if totalsum == 0:
            sciscore[school] = 0
        else:
            sciscore[school] = totalsum/totalcount

    else:
        sciscore[school] = 0
sciscore

C:\Users\thewa\AppData\Local\Temp\ipykernel_9780\3806142921.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  info = info[info["SY"] == 2022][info["AssessGroup"] == "All Students"][info["Indicator_Label"] == "Average Scaled Score"].reset_index(drop=True)

{'PS023': 0,
 'PS045': 47.3143,
 'PS162': 0,
 'PS189': 55.1818,
 'PS195': 50.91215,
 'PS246': 49.25,
 'PS108': 58.6667,
 'PS311': 45.8,
 'PS312': 54.9047,
 'PS043': 0,
 'PS076': 0,
 'PS179': 55.2241,
 'PS180': 58.1048,
 'PS244': 0,
 'PS259': 56.9167,
 'PS268': 56.0769,
 'PS336': 0,
 'PS366': 48.9727,
 'PS031': 0,
 'PS103': 49.4995,
 'PS104': 49.3718,
 'PS218': 0,
 'PS413': 52.8667,
 'PS414': 0,
 'PS011': 51.316950000000006,
 'PS029': 34.8125,
 'PS109': 46.5,
 'PS188': 36.2821,
 'PS192': 0,
 'PS196': 53.9463,
 'PS197': 47.5282,
 'PS231': 48.9286,
 'PS262': 53.3704,
 'PS354': 0,
 'PS079': 0,
 'PS085': 0,
 'PS111': 49.1515,
 'PS175': 0,
 'PS293': 0,
 'PS392': 47.5882,
 'PS072': 57.6,
 'PS073': 53.7939,
 'PS174': 56.4082,
 'PS227': 0,
 'PS309': 0,
 'PS051': 54.095200000000006,
 'PS170': 49.520849999999996,
 'PS184': 0,
 'PS201': 0,
 'PS294': 0,
 'PS018': 52.6643,
 'PS055': 45.8182,
 'PS082': 51.24,
 'PS223': 0,
 'PS316': 0,
 'PS140': 0,
 'PS185': 42.3229,
 'PS186': 52.3077,
 'PS400': 45.67595,
 'PS041': 0,
 'PS050': 60.7688,
 'PS058': 60.32795,
 'PS152': 0,
 'PS199': 61.523,
 'PS243': 0,
 'PS270': 0,
 'PS306': 0,
 'PS141': 0,
 'PS292': 0,
 'PS299': 58.7955,
 'PS333': 56.32475,
 'PS388': 61.9745,
 'PS066': 64.354,
 'PS068': 60.738949999999996,
 'PS143': 57.5687,
 'PS264': 57.14595,
 'PS398': 54.52065,
 'PS052': 60.2011,
 'PS065': 58.8431,
 'PS080': 50.2407,
 'PS094': 58.5128,
 'PS095': 55.2824,
 'PS155': 46.9189,
 'PS159': 49.6897,
 'PS169': 52.719,
 'PS337': 44.2857,
 'PS064': 0,
 'PS216': 0,
 'PS271': 56.6622,
 'PS272': 59.9036,
 'PS273': 58.4417,
 'PS154': 36.0784,
 'PS351': 38.9211,
 'PS401': 39.4211,
 'PS074': 49.3913,
 'PS324': 50.575,
 'PS059': 0,
 'PS015': 47.007,
 'PS032': 42.2262,
 'PS096': 52.5,
 'PS098': 52.96725,
 'PS190': 64.78575000000001,
 'PS241': 32.2143,
 'PS242': 50.542100000000005,
 'PS266': 49.97325,
 'PS115': 64.5625,
 'PS142': 54.3333,
 'PS187': 51.466,
 'PS295': 51.1429,
 'PS027': 0,
 'PS110': 0,
 'PS117': 0,
 'PS405': 0,
 'PS105': 43.58695,
 'PS288': 51.63195,
 'PS289': 52.10565,
 'PS406': 55.0462,
 'PS010': 52.8598,
 'PS112': 0,
 'PS122': 0,
 'PS209': 0,
 'PS057': 59.6154,
 'PS093': 0,
 'PS145': 42.7241,
 'PS153': 51.0645,
 'PS158': 48.7882,
 'PS325': 0,
 'PS404': 44.664,
 'PS156': 0,
 'PS194': 0,
 'PS224': 53.7083,
 'PS286': 60.4909,
 'PS394': 52.70655,
 'PS419': 57.1818,
 'PS420': 65.8462,
 'PS037': 50.4444,
 'PS202': 50.2727,
 'PS220': 52.08685,
 'PS298': 54.0909,
 'PS310': 55.13735,
 'PS038': 0,
 'PS047': 0,
 'PS237': 49.918350000000004,
 'PS359': 53.4054,
 'PS215': 0,
 'PS322': 0,
 'PS344': 50.0741,
 'PS034': 52.5,
 'PS069': 52.2298,
 'PS206': 0,
 'PS247': 0,
 'PS263': 55.5652,
 'PS274': 48.7727,
 'PS303': 0,
 'PS416': 52.6491,
 'PS417': 59.7027,
 'PS044': 0,
 'PS067': 0,
 'PS077': 48.7738,
 'PS084': 53.2157,
 'PS166': 0,
 'PS204': 48.5714,
 'PS205': 0,
 'PS208': 50.8647,
 'PS302': 38.482150000000004,
 'PS364': 45.5408,
 'PS374': 0,
 'PS033': 51.9667,
 'PS056': 0,
 'PS091': 57.697,
 'PS181': 56.25,
 'PS305': 54.428,
 'PS357': 0,
 'PS071': 50.9545,
 'PS183': 50.609049999999996,
 'PS269': 0,
 'PS300': 0,
 'PS317': 45.3333,
 'PS007': 0,
 'PS022': 45.94445,
 'PS049': 52.3631,
 'PS118': 54.822900000000004,
 'PS147': 0,
 'PS157': 61.2055,
 'PS217': 0,
 'PS078': 68.4211,
 'PS126': 0,
 'PS131': 42.7097,
 'PS139': 53.7941,
 'PS352': 50.6,
 'PS353': 0,
 'PS021': 0,
 'PS165': 0,
 'PS200': 45.6444,
 'PS219': 0,
 'PS418': 0,
 'PS232': 35.4667,
 'PS258': 54.4844,
 'PS182': 0,
 'PS229': 0,
 'PS328': 0,
 'PS167': 58.25,
 'PS198': 50.6429,
 'PS253': 57.768,
 'PS255': 0,
 'PS256': 0,
 'PS365': 40.4023,
 'PS382': 41.1442,
 'PS304': 0,
 'PS107': 0,
 'PS138': 53.40265,
 'PS193': 56.9375,
 'PS315': 61.2083,
 'PS320': 66.4118,
 'PS390': 0,
 'PS391': 54.06335,
 'PS210': 0,
 'PS250': 0,
 'PS173': 55.33135,
 'PS191': 61.2165,
 'PS308': 0,
 'PS086': 0,
 'PS149': 0,
 'PS161': 46.7333,
 'PS177': 47.87765,
 'PS301': 0,
 'PS319': 0,
 'PS347': 0,
 'PS408': 47.5,
 'PS024': 45.536649999999995,
 'PS025': 55.8,
 'PS120': 0,
 'PS249': 0,
 'PS260': 0,
 'PS334': 0,
 'PS001': 45.9815,
 'PS040': 54.0282,
 'PS087': 0,
 'PS128': 0,
 'PS234': 0,
 'PS313': 51.5769,
 'PS367': 50.1056,
 'PS383': 44.8696,
 'PS385': 42.5484,
 'PS083': 60.32,
 'PS129': 0,
 'PS240': 0,
 'PS284': 0,
 'PS411': 51.302099999999996,
 'PS285': 0,
 'PS017': 0,
 'PS239': 0,
 'PS267': 0,
 'PS355': 0,
 'PS356': 58.0907,
 'PS409': 61.4348,
 'PS008': 0,
 'PS137': 52.68425,
 'PS407': 57.5833,
 'PS410': 48.77343333333334,
 'PS070': 43.8214,
 'PS134': 50.9478,
 'PS135': 52.5604,
 'PS339': 52.4545,
 'PS378': 56.7647,
 'PS380': 60.65,
 'PS245': 43.76,
 'PS277': 0,
 'PS278': 54.3542,
 'PS280': 43.2716,
 'PS036': 45.38023333333334,
 'PS099': 0,
 'PS113': 53.4314,
 'PS020': 50.471900000000005,
 'PS276': 55.9725,
 'PS381': 48.49145,
 'PS063': 56.7059,
 'PS124': 47.95065,
 'PI004': 52.282799999999995,
 'PS106': 41.5,
 'PS176': 0,
 'PS399': 44.6667,
 'PS009': 60.2,
 'PS101': 60.3873,
 'PS230': 43.6522,
 'PS233': 44.1135,
 'PS331': 47.74323333333333,
 'PS168': 0,
 'PS211': 52.7344,
 'PS343': 45.4688}

In [52]:
enroll["Scores"] = sciscore.values()
enroll = enroll[enroll["Scores"] != 0]
enroll

,SchoolIdentifier,OrganizationName,Preschool,Preschool,KindergartenFullTime,KindergartenPartTime,FirstGrade,SecondGrade,ThirdGrade,FourthGrade,FifthGrade,SixthGrade,SeventhGrade,EighthGrade,NinethGrade,TenthGrade,EleventhGrade,TwelvethGrade,Total,Scores
1,PS045,BRISTOL ELEMENTARY SCHOOL,150,150,33,0,38,36,42,33,39,36,0,0,0,0,0,0,407,47.314300
3,PS189,MONKTON CENTRAL SCHOOL,0,0,24,0,15,19,15,16,23,14,0,0,0,0,0,0,126,55.181800
4,PS195,MT ABRAHAM UHS #28,0,0,0,0,0,0,0,0,0,0,109,107,109,100,109,116,650,50.912150
5,PS246,ROBINSON SCHOOL,0,0,17,0,14,12,13,22,21,17,0,0,0,0,0,0,116,49.250000
6,PS108,FERRISBURGH CENTRAL SCHOOL,24,24,31,0,21,17,18,20,21,15,0,0,0,0,0,0,167,58.666700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,PS230,POULTNEY HIGH SCHOOL,0,0,0,0,0,0,0,0,0,0,43,53,42,44,35,30,247,43.652200
285,PS233,PROCTOR JR/SR HIGH SCHOOL,0,0,0,0,0,0,0,0,0,0,21,17,27,28,19,23,135,44.113500
286,PS331,WEST RUTLAND SCHOOL,24,24,31,0,24,22,25,28,17,27,29,27,29,28,18,16,345,47.743233
288,PS211,NORTHFIELD MIDDLE/HIGH SCHOOL,0,0,0,0,0,0,0,0,0,36,37,38,39,37,39,39,265,52.734400
289,PS343,WILLIAMSTOWN ELEM SCHOOL,45,45,34,0,31,30,36,46,34,0,0,0,0,0,0,0,256,45.468800

In [53]:
import random
random.seed(1)

hsenroll = enroll[(enroll["NinethGrade"] != 0) | (enroll["TenthGrade"] != 0) | (enroll["EleventhGrade"] != 0) | (enroll["TwelvethGrade"] != 0)].sort_values("Total").reset_index(drop = True)
msenroll = enroll[(enroll["NinethGrade"] == 0) & (enroll["TenthGrade"] == 0) & (enroll["EleventhGrade"] == 0) & (enroll["TwelvethGrade"] == 0)].sort_values("Total").reset_index(drop = True)

hslow = random.sample(range(1, round(len(hsenroll)/3)), 10)
hsmid = random.sample(range(round(len(hsenroll)/3)+1, 2*round(len(hsenroll)/3)), 10)
hshigh = random.sample(range(2*round(len(hsenroll)/3), len(hsenroll)), 10)

mslow = random.sample(range(1, round(len(msenroll)/3)), 10)
msmid = random.sample(range(round(len(msenroll)/3)+1, 2*round(len(msenroll)/3)), 10)
mshigh = random.sample(range(2*round(len(msenroll)/3), len(msenroll)), 10)

In [54]:
hshigh

[48, 42, 41, 43, 35, 39, 34, 45, 44, 50]

In [55]:
hsidh = hsenroll.iloc[hshigh]["SchoolIdentifier"]
hsidm = hsenroll.iloc[hsmid]["SchoolIdentifier"]
hsidl = hsenroll.iloc[hslow]["SchoolIdentifier"]

msidh = msenroll.iloc[mshigh]["SchoolIdentifier"]
msidm = msenroll.iloc[msmid]["SchoolIdentifier"]
msidl = msenroll.iloc[mslow]["SchoolIdentifier"]

In [56]:
hsidh

48    PS406
42    PS187
41    PS305
43    PS199
35    PS138
39    PS208
34    PS180
45    PS253
44    PS040
50    PS388
Name: SchoolIdentifier, dtype: object

In [57]:
hssdh = enroll[enroll["SchoolIdentifier"].isin(hsidh)].reset_index(drop=True)
hssdm = enroll[enroll["SchoolIdentifier"].isin(hsidm)].reset_index(drop=True)
hssdl = enroll[enroll["SchoolIdentifier"].isin(hsidl)].reset_index(drop=True)

mssdh = enroll[enroll["SchoolIdentifier"].isin(msidh)].reset_index(drop=True)
mssdm = enroll[enroll["SchoolIdentifier"].isin(msidm)].reset_index(drop=True)
mssdl = enroll[enroll["SchoolIdentifier"].isin(msidl)].reset_index(drop=True)

In [58]:
list(hssdl["Scores"])

[51.316950000000006,
 50.542100000000005,
 50.0741,
 59.7027,
 68.4211,
 53.7941,
 46.7333,
 52.282799999999995,
 43.6522,
 52.7344]

Subgroup

In [59]:
info = pd.read_csv("Vermont Data/Vermont Science Data.csv")
set(info[infg["AssessGroup"] == "Gender"]["AssessLabel"])

{'Female', 'Male'}

In [62]:
enroll = pd.read_excel("Vermont Data/Vermont Enrollment Info.xlsx")
enroll = enrollg[enrollg["SchoolYear"] == 2022][["SchoolIdentifier", "OrganizationName", "Preschool", "Preschool", "KindergartenFullTime", "KindergartenPartTime", "FirstGrade", "SecondGrade", "ThirdGrade", "FourthGrade", "FifthGrade", "SixthGrade", "SeventhGrade", "EighthGrade", "NinethGrade", "TenthGrade", "EleventhGrade", "TwelvethGrade", "Total"]].reset_index(drop=True)

infog = infog[infog["SY"] == 2022][infog["AssessGroup"] == "Gender"][infog["AssessLabel"] == "Female"][infog["Indicator_Label"] == "Average Scaled Score"].reset_index(drop=True)

sciscoreg = {}
infoorg = list(info["OrganizationIdentifier"])

for school in enroll["SchoolIdentifier"]:
    if school in infoorg:
        scilistg = (infog[infog["OrganizationIdentifier"] == school]["SchoolValue"])
        totalsum = 0
        totalcount = 0
        for val in scilist:
            if "." in val:
                totalsum += float(val)
                totalcount += 1
        
        if totalsum == 0:
            sciscoreg[school] = 0
        else:
            sciscoreg[school] = totalsum/totalcount

    else:
        sciscoreg[school] = 0
sciscoreg

C:\Users\thewa\AppData\Local\Temp\ipykernel_9780\490381731.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  infog = infog[infog["SY"] == 2022][infog["AssessGroup"] == "Gender"][infog["AssessLabel"] == "Female"][infog["Indicator_Label"] == "Average Scaled Score"].reset_index(drop=True)
C:\Users\thewa\AppData\Local\Temp\ipykernel_9780\490381731.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  infog = infog[infog["SY"] == 2022][infog["AssessGroup"] == "Gender"][infog["AssessLabel"] == "Female"][infog["Indicator_Label"] == "Average Scaled Score"].reset_index(drop=True)

{'PS045': 45.4688,
 'PS189': 45.4688,
 'PS195': 45.4688,
 'PS246': 45.4688,
 'PS108': 45.4688,
 'PS311': 45.4688,
 'PS312': 45.4688,
 'PS179': 45.4688,
 'PS180': 45.4688,
 'PS259': 45.4688,
 'PS268': 45.4688,
 'PS366': 45.4688,
 'PS103': 45.4688,
 'PS104': 45.4688,
 'PS413': 45.4688,
 'PS011': 45.4688,
 'PS029': 45.4688,
 'PS109': 45.4688,
 'PS188': 45.4688,
 'PS196': 45.4688,
 'PS197': 45.4688,
 'PS231': 45.4688,
 'PS262': 45.4688,
 'PS111': 45.4688,
 'PS392': 45.4688,
 'PS072': 45.4688,
 'PS073': 45.4688,
 'PS174': 45.4688,
 'PS051': 45.4688,
 'PS170': 45.4688,
 'PS018': 45.4688,
 'PS055': 45.4688,
 'PS082': 45.4688,
 'PS185': 45.4688,
 'PS186': 45.4688,
 'PS400': 45.4688,
 'PS050': 45.4688,
 'PS058': 45.4688,
 'PS199': 45.4688,
 'PS299': 45.4688,
 'PS333': 45.4688,
 'PS388': 45.4688,
 'PS066': 45.4688,
 'PS068': 45.4688,
 'PS143': 45.4688,
 'PS264': 45.4688,
 'PS398': 45.4688,
 'PS052': 45.4688,
 'PS065': 45.4688,
 'PS080': 45.4688,
 'PS094': 45.4688,
 'PS095': 45.4688,
 'PS155': 45.4688,
 'PS159': 45.4688,
 'PS169': 45.4688,
 'PS337': 45.4688,
 'PS271': 45.4688,
 'PS272': 45.4688,
 'PS273': 45.4688,
 'PS154': 45.4688,
 'PS351': 45.4688,
 'PS401': 45.4688,
 'PS074': 45.4688,
 'PS324': 45.4688,
 'PS015': 45.4688,
 'PS032': 45.4688,
 'PS096': 45.4688,
 'PS098': 45.4688,
 'PS190': 45.4688,
 'PS241': 45.4688,
 'PS242': 45.4688,
 'PS266': 45.4688,
 'PS115': 45.4688,
 'PS142': 45.4688,
 'PS187': 45.4688,
 'PS295': 45.4688,
 'PS105': 45.4688,
 'PS288': 45.4688,
 'PS289': 45.4688,
 'PS406': 45.4688,
 'PS010': 45.4688,
 'PS057': 45.4688,
 'PS145': 45.4688,
 'PS153': 45.4688,
 'PS158': 45.4688,
 'PS404': 45.4688,
 'PS224': 45.4688,
 'PS286': 45.4688,
 'PS394': 45.4688,
 'PS419': 45.4688,
 'PS420': 45.4688,
 'PS037': 45.4688,
 'PS202': 45.4688,
 'PS220': 45.4688,
 'PS298': 45.4688,
 'PS310': 45.4688,
 'PS237': 45.4688,
 'PS359': 45.4688,
 'PS344': 45.4688,
 'PS034': 45.4688,
 'PS069': 45.4688,
 'PS263': 45.4688,
 'PS274': 45.4688,
 'PS416': 45.4688,
 'PS417': 45.4688,
 'PS077': 45.4688,
 'PS084': 45.4688,
 'PS204': 45.4688,
 'PS208': 45.4688,
 'PS302': 45.4688,
 'PS364': 45.4688,
 'PS033': 45.4688,
 'PS091': 45.4688,
 'PS181': 45.4688,
 'PS305': 45.4688,
 'PS071': 45.4688,
 'PS183': 45.4688,
 'PS317': 45.4688,
 'PS022': 45.4688,
 'PS049': 45.4688,
 'PS118': 45.4688,
 'PS157': 45.4688,
 'PS078': 45.4688,
 'PS131': 45.4688,
 'PS139': 45.4688,
 'PS352': 45.4688,
 'PS200': 45.4688,
 'PS232': 45.4688,
 'PS258': 45.4688,
 'PS167': 45.4688,
 'PS198': 45.4688,
 'PS253': 45.4688,
 'PS365': 45.4688,
 'PS382': 45.4688,
 'PS138': 45.4688,
 'PS193': 45.4688,
 'PS315': 45.4688,
 'PS320': 45.4688,
 'PS391': 45.4688,
 'PS173': 45.4688,
 'PS191': 45.4688,
 'PS161': 45.4688,
 'PS177': 45.4688,
 'PS408': 45.4688,
 'PS024': 45.4688,
 'PS025': 45.4688,
 'PS001': 45.4688,
 'PS040': 45.4688,
 'PS313': 45.4688,
 'PS367': 45.4688,
 'PS383': 45.4688,
 'PS385': 45.4688,
 'PS083': 45.4688,
 'PS411': 45.4688,
 'PS356': 45.4688,
 'PS409': 45.4688,
 'PS137': 45.4688,
 'PS407': 45.4688,
 'PS410': 45.4688,
 'PS070': 45.4688,
 'PS134': 45.4688,
 'PS135': 45.4688,
 'PS339': 45.4688,
 'PS378': 45.4688,
 'PS380': 45.4688,
 'PS245': 45.4688,
 'PS278': 45.4688,
 'PS280': 45.4688,
 'PS036': 45.4688,
 'PS113': 45.4688,
 'PS020': 45.4688,
 'PS276': 45.4688,
 'PS381': 45.4688,
 'PS063': 45.4688,
 'PS124': 45.4688,
 'PI004': 45.4688,
 'PS106': 45.4688,
 'PS399': 45.4688,
 'PS009': 45.4688,
 'PS101': 45.4688,
 'PS230': 45.4688,
 'PS233': 45.4688,
 'PS331': 45.4688,
 'PS211': 45.4688,
 'PS343': 45.4688}

In [63]:
enrollg["Scores"] = sciscoreg.values()
enrollg = enrollg[enrollg["Scores"] != 0]
enrollg

ValueError: Length of values (185) does not match length of index (290)

:

In [ ]:
import random
random.seed(1)

hsenrollg = enrollg[(enrollg["NinethGrade"] != 0) | (enrollg["TenthGrade"] != 0) | (enrollg["EleventhGrade"] != 0) | (enrollg["TwelvethGrade"] != 0)].sort_values("Total").reset_index(drop = True)
msenrollg = enrollg[(enrollg["NinethGrade"] == 0) & (enrollg["TenthGrade"] == 0) & (enrollg["EleventhGrade"] == 0) & (enrollg["TwelvethGrade"] == 0)].sort_values("Total").reset_index(drop = True)

hslowg = random.sample(range(1, round(len(hsenrollg)/3)), 5)
hsmidg = random.sample(range(round(len(hsenrollg)/3)+1, 2*round(len(hsenrollg)/3)), 5)
hshighg = random.sample(range(2*round(len(hsenrollg)/3), len(hsenrollg)), 5)

mslowg = random.sample(range(1, round(len(msenrollg)/3)), 5)
msmidg = random.sample(range(round(len(msenrollg)/3)+1, 2*round(len(msenrollg)/3)), 5)
mshighg = random.sample(range(2*round(len(msenrollg)/3), len(msenrollg)), 5)

In [ ]:
hshighg

[27, 33, 26, 32, 34]

In [ ]:
hsidhg = hsenrollg.iloc[hshighg]["SchoolIdentifier"]
hsidmg = hsenrollg.iloc[hsmidg]["SchoolIdentifier"]
hsidlg = hsenrollg.iloc[hslowg]["SchoolIdentifier"]

msidhg = msenrollg.iloc[mshighg]["SchoolIdentifier"]
msidmg = msenrollg.iloc[msmidg]["SchoolIdentifier"]
msidlg = msenrollg.iloc[mslowg]["SchoolIdentifier"]

In [ ]:
hssdhg = enroll[enroll["SchoolIdentifier"].isin(hsidhg)].reset_index(drop=True)
hssdmg = enroll[enroll["SchoolIdentifier"].isin(hsidmg)].reset_index(drop=True)
hssdlg = enroll[enroll["SchoolIdentifier"].isin(hsidlg)].reset_index(drop=True)

mssdhg = enroll[enroll["SchoolIdentifier"].isin(msidhg)].reset_index(drop=True)
mssdmg = enroll[enroll["SchoolIdentifier"].isin(msidmg)].reset_index(drop=True)
mssdlg = enroll[enroll["SchoolIdentifier"].isin(msidlg)].reset_index(drop=True)

In [ ]:
list(mssdlg["Scores"])

[50.1176, 46.5217, 41.2286, 54.9286, 59.5882]